### ISSUE TITLE
Set "Number of Z Steps" to zero at end of 3d grid scan script

### ISSUE THREAD

**Issue by ndg63276** [DiamondLightSource/python-artemis#114]
The way that the low level grid scan program (on the smargon controller) decides if it is a 2d or 3d grid scan is just (pseudo-code)
```
is_3d_grid_scan = no_of_z_steps > 0
```
So if we do a 3d grid scan, and then attempt a 2d grid scan, we end up with two 3d grid scans, as the number of z steps is still greater than zero. We should put it back to zero at the end of each 3d grid scan.

**Comment by bentom08** [comment]
We should be handling this at the start of each scan (i.e. setting z_steps to 0 for a 2D scan) rather than assuming the controller is in the correct state (e.g. if we run a 3D scan and encounter an exception before artemis resets the z_steps we would encounter the same problem).

We already set the z_steps for 2D scans in artemis, so it looks like an issue with the hacky way we currently call artemis from GDA, rather than artemis itself.

**Comment by DominicOram** [comment]
Do the move without waiting for it to finish (e.g. `set` rather than `mv`)
