### ISSUE TITLE
Simulation: Write tickit simulations for Synchrotron mode

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#145]
For us to be able to run system tests properly against S03 we will need a simple IOC that gives us the Synchroton Mode

We can do this using the real `db` file and then the `EpicsAdapter` in `tickit`. See https://github.com/dls-controls/tickit/tree/master/tickit/devices/femto

**Comment by callumforrester** [comment]
Would https://github.com/dls-controls/tickit not be a better home for simulated devices?

**Comment by DominicOram** [comment]
Sorry, I meant adding it in such that S03 started it. You're right the code should be elsewhere, I think separate from tickit core though

**Comment by abbiemery** [comment]
This tickit is essentially complete. The [tickit-devices](https://github.com/dls-controls/tickit-devices/tree/main) repo has a Dockerfile build in which will create an image which can be run within [S03](https://gitlab.diamond.ac.uk/controls/python3/s03_utils/-/tree/master). I've added the `tickit-devices` image to S03, and set up the synchrotron device which will run the synchrotron config on start up.

In summary, the synchrotron device is there when you start s03 now, and as such the system tests should work. I have not merged the PR because the `get_value` test is brittle and not appropriate, it was put in for testing the connections between the simulations and artemis but is no longer relevant. It will of course work on start up, as the stored values are those of the tickit device defaults, but should any of them change it fails. Since there is not a way for ophyd (that i'm aware of?) to set these values, since they're done via a tcp connection, this test needs removing and a useful one put in it's place.
