### ISSUE TITLE
Create devices when artemis starts

### ISSUE THREAD

**Issue by MattPrit** [DiamondLightSource/python-artemis#221]
Currently devices are created every time a plan is run. Some devices may persist once the plan has completed, so when a plan is repeated multiple times, the number of active devices can grow large. It may be beneficial to just create devices once when artemis starts up, and then pass these devices into the plan.

**Comment by evalott100** [comment]
I've implemented this by adding global variables in artemis/devices/fast_grid_scan_composite.py and artemis/devices/eiger.py which initialized on the first call of get_plan and then reused rather than reinitialized. The eiger is the only device which takes parameters and is updated each time get_plan is called.
