### ISSUE TITLE
Remove prefix from machine PVs in S03 and make sure ports don't conflict

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#516]
Some system tests (`read_hardware_for_ispyb`) have started failing because some new PVs which `fgs` connects to are not present:

```
TimeoutError: Failed to connect to all signals: fgs.synchrotron.machine_status.synchrotron_mode (CS-CS-MSTAT-01:MODE), fgs.synchrotron.machine_status.user_countdown (CS-CS-MSTAT-01:USERCOUNTDN), fgs.synchrotron.machine_status.beam_energy (CS-CS-MSTAT-01:BEAMENERGY), fgs.synchrotron.top_up.start_countdown (SR-CS-FILL-01:COUNTDOWN), fgs.synchrotron.top_up.end_countdown (SR-CS-FILL-01:ENDCOUNTDN), fgs.synchrotron.ring_current (SR-DI-DCCT-01:SIGNAL)
```

**Comment by DominicOram** [comment]
So this does work for me but that's because it's looking at the real PVs. `S03` does have fake PVs but they're on `BL03S-CS-CS...`, which is hard to fit in given that there is no equivalent prefix for the real case. We will need to fix this when we do https://github.com/DiamondLightSource/python-artemis/issues/458 as then the test won't work against the real PV any more. I think the solution is to remove the additional prefix in S03
