### ISSUE TITLE
We need a coherent policy for deciding whether utils go in dodal or hyperion/artemis

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#580]
For example, there are some OAV utility functions and calculations in both dodal and artemis

**Comment by DominicOram** [comment]
Needs wider discussion with @callumforrester, @coretl, @graeme-winter  etc. Then we should write in documentation for `dodal`

**Comment by graeme-winter** [comment]
Discovery: it should not be _that_ hard if everything is public open source 🤷‍♂️

**Comment by coretl** [comment]
> Just so I understand the context: `hyperion` ! = `artemis` here right?

I was using them interchangeably, I meant that if we only have a single application for MX (assuming artemis will evolve into hyperion rather than coexist long term), then it's probably easier to leave things like the OAV utils there until we have a need for it in something outside artemis/hyperion. 

> Discovery: it should not be _that_ hard if everything is public open source man_shrugging

Agreed

**Comment by callumforrester** [comment]
If we are still saying that dodal is specifically about devices (are we?) then I think such a policy can be pretty simple: dodal utils are only to do with generic device creation and shouldn't fulfill any MX science requirements, that should be artemis/hyperion's job.
