### ISSUE TITLE
Position table not stored correctly

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#60]
During testing on i03 it was found that the position table was not being stored correctly in IspyB. This was fixed on the beamline by not storing it at all but it should be fixed properly to give correct position information in ispyb etc.

**Comment by DominicOram** [comment]
@bentom08 I think you had some more details on this, could you add here?

**Comment by bentom08** [comment]
This was due to a misunderstanding of how the update_dc_position stored procedure in ispyb-api works. It needs to be called after the scan has been inserted into the DataCollection table, and it needs to be given the dc_id as "id" in its params dictionary. The stored procedure will then insert a row into the position table and update the corresponding DataCollection row with a foreign key.

**Comment by DominicOram** [comment]
Fixed by https://github.com/DiamondLightSource/python-artemis/pull/74
